// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneReport.Data;

#nullable disable

namespace OneReport.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313205408_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OneReport.Data.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection_string");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_data_sources");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_data_sources_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_data_sources_name");

                    b.ToTable("data_sources", (string)null);
                });

            modelBuilder.Entity("OneReport.Data.Entities.ReportColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aggregation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("aggregation");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_type");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("field_name");

                    b.Property<string>("Format")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("format");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_definition_id");

                    b.Property<int?>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_report_columns");

                    b.HasIndex("DisplayOrder")
                        .HasDatabaseName("ix_report_columns_display_order");

                    b.HasIndex("ReportDefinitionId")
                        .HasDatabaseName("ix_report_columns_report_definition_id");

                    b.ToTable("report_columns", (string)null);
                });

            modelBuilder.Entity("OneReport.Data.Entities.ReportDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DataSourceConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_source_config");

                    b.Property<string>("DataSourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_source_type");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("QueryTemplate")
                        .HasColumnType("text")
                        .HasColumnName("query_template");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_report_definitions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_report_definitions_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_report_definitions_is_active");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_report_definitions_name");

                    b.ToTable("report_definitions", (string)null);
                });

            modelBuilder.Entity("OneReport.Data.Entities.ReportExportHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("ExportFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("export_format");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Parameters")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<long?>("RecordCount")
                        .HasColumnType("bigint")
                        .HasColumnName("record_count");

                    b.Property<Guid>("ReportDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_definition_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_report_export_histories");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_report_export_histories_created_at");

                    b.HasIndex("ReportDefinitionId")
                        .HasDatabaseName("ix_report_export_histories_report_definition_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_report_export_histories_status");

                    b.ToTable("report_export_histories", (string)null);
                });

            modelBuilder.Entity("OneReport.Data.Entities.ReportColumn", b =>
                {
                    b.HasOne("OneReport.Data.Entities.ReportDefinition", "ReportDefinition")
                        .WithMany("Columns")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_columns_report_definitions_report_definition_id");

                    b.Navigation("ReportDefinition");
                });

            modelBuilder.Entity("OneReport.Data.Entities.ReportExportHistory", b =>
                {
                    b.HasOne("OneReport.Data.Entities.ReportDefinition", "ReportDefinition")
                        .WithMany("ExportHistories")
                        .HasForeignKey("ReportDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_export_histories_report_definitions_report_definitio");

                    b.Navigation("ReportDefinition");
                });

            modelBuilder.Entity("OneReport.Data.Entities.ReportDefinition", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("ExportHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
